### ISSUE TITLE
asking for help

### ISSUE THREAD

**Issue by 19940312** [JeyesHan/msrlOB#1]
Sorry to bother you, but I am strongly desired to achieve the object detection via reinforcement learning, and I don't know how to configure my dataset when I am ready to run this code. Could you give me a detailed description? Thx very much.

**Comment by HelloJianHan** [comment]
You just need to assign the pth of  Pascal VOC2007 dataset to "path_voc" variable in main.py. Note that this repo is an incomplete work done before and there's no evaluation code available. You can write 
 it yourself.
